### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by AlfredMenezes**
I'm adding a link to my new online cryptography course. This is a course that I teach each year to a large class of undergraduate students at the University of Waterloo (Canada).

### CODE REVIEW

**Review by sobolevn — APPROVED** [review]
Looks great, thank you!

**Comment by sobolevn** [comment]
But please fix the CI failure :)

**Comment by AlfredMenezes** [comment]
I believe I have fixed the CI failure. (Apologies, this is my first time using Github!)

**Comment by sobolevn** [comment]
@AlfredMenezes congrats on your first PR! 🎉

**Comment by AlfredMenezes** [comment]
Thanks! Now I know what my students mean when they say "pull request".

**Pull request merged**
