### PR TITLE
Add article on how to generate secure random numbers.

### PR DESCRIPTION
**Pull request by kdeldycke**
Also add missing Article section.

### CODE REVIEW

**Comment by QuentinPerez** [comment]
👍

**Comment by sobolevn** [comment]
"articles" section is a good idea! do you have any other ideas on the recommended materials?

**Comment by kdeldycke** [comment]
@sobolevn : No other articles I think of right now. Maybe @QuentinPerez has some ideas of other noteworthy articles?

**Comment by sobolevn** [comment]
ok, I am merging this anyway, but we can continue our discussion here.

**Comment by kdeldycke** [comment]
Thanks @sobolevn for the quick merge! I'll surely create a new PR if I stumble upon a good candidate for awesome cryptography articles.

**Pull request merged**
