### PR TITLE
Added libraries, SDK docs, gitHub resources, and concepts covering Tr…

### PR DESCRIPTION
**Pull request by madison-kerndt**
…ansform Encryption.

### CODE REVIEW

**Comment by sobolevn** [comment]
@madison-kerndt awesome! Thanks a lot.
Please, fix the falling test and I am ready to merge it.

**Comment by madison-kerndt** [comment]
@sobolevn I went ahead and put the added items into alphabetical order. I am still running into errors with valid URLs that return anything other than a 200 status code. The two links that are failing the build are:
* https://cryptobook.nakov.com that returns a 204
* https://blog.ironcorelabs.com that returns a 409
Yet the links are valid in terms of navigating to live sites. 

What do you recommend as the best next step?

**Comment by sobolevn** [comment]
Can you please also remove this dependency that check links?

It is bot useful anyway. And causes too much trouble for maintainers.
Thanks!

**Comment by madison-kerndt** [comment]
No problem! Looks like the `yarn test`s are passing now. Thanks for helping me solve the issue!

**Comment by sobolevn** [comment]
🎉

**Pull request merged**
