### PR TITLE
libVES.c

### PR DESCRIPTION
**Pull request by vesvault**
# Encryption for data at-rest made practical
[VESvault](https://vesvault.com): Encrypt Evertyhing without fear of losing the Key.
- Share encrypted data with your friends and colleagues.
- Securely exchange temporary keys with new users.
- [Viral Encrypted Security (VES)](https://www.vesvault.com/#vault): Recover your data through a viral network of friends in case of the encryption key loss.
## Cloud based end-to-end encryption API
[VES.host](https://ves.host): VESvault API integration center.
[libVES.c](https://github.com/vesvault/libVES.c): C library and command line utility.
[libVES.js](https://github.com/vesvault/libVES): JS library

### CODE REVIEW

**Comment by vesvault** [comment]
libVES.js

**Comment by vesvault** [comment]
VES command line utility

**Comment by sobolevn** [comment]
@vesvault can you please fix the travis build?

**Comment by vesvault** [comment]
@sobolevn Fixed a duplicate link, travis build has passed now, my apologies -

**Comment by sobolevn** [comment]
Thanks!

**Pull request merged**
