### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by drgonzo31**
Added Bruce Schneiers paper on cryptoanalysis.

### CODE REVIEW

**Comment by sobolevn** [comment]
Could you please fix the issues with travis?

For some reason https://ironcorelabs.com/products/ironsftp page is gone, it should be changed.

**Comment by drgonzo31** [comment]
Sure will do.

**Comment by sobolevn** [comment]
Thanks for the awesome addition!

**Comment by sobolevn** [comment]
@drgonzo31 congrats with the first pull request! 🎉

**Pull request merged**
