### PR TITLE
Added links to Themis wrappers

### PR DESCRIPTION
**Pull request by vixentael**
I found that Themis was mentioned in ObjC section only, however, this is C-core library ported to many languages/platforms.

I've added Themis to C, Go, Js, Java, PHP, Python, Ruby, Swift sections, and updated its description.

### CODE REVIEW

**Comment by sobolevn** [comment]
@vixentael thanks! Maybe instead we should only add it into `C` section with a note, that there are a lot of different wrappers for different languages?

**Comment by vixentael** [comment]
Yes, I've noted in C section about wrappers and languages.

Before making this PR I've checked how similar libraries are described. I took libsodium and scrypt as examples. 

Moreover I thought that developers will check their favorite languages/sections to pick up lib, instead of looking for C-core with multiple wrappers.

**Comment by sobolevn** [comment]
There is one problem, since we don't allow non-unique links. 
With `libsodium` each link points to its own repo.

**Comment by vixentael** [comment]
I see. Let me update links to point to different language guides and see maybe it helps

**Comment by vixentael** [comment]
Sorry, I might missed the rule about alphabetic order in the contributing guide. Fixed order.

**Comment by sobolevn** [comment]
Thanks! Great.

**Comment by sobolevn** [comment]
@vixentael btw, here you are: https://twitter.com/awe_crypto_bot/status/914505525001441280

**Comment by vixentael** [comment]
Ahhh, so nice!

Thank you for your hard work! ❤️

**Pull request merged**
